name: Trigger on File Modification

on:
  push:
    paths:
      - 'experiment_definition.yaml'
  pull_request:
    paths:
      - 'experiment_definition.yaml'

permissions:
  contents: write  # Allow pushing changes back to repo

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SSH_CONFIG_PATH: ${{ secrets.SSH_CONFIG_PATH }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: true  # Allows git push to work

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt      

    - name: NeuroCI Run
      run: python ./neuroci_code/main.py
