name: Trigger on File Modification

on:
  push:
    paths:
      - 'experiment_definition.yaml'
  pull_request:
    paths:
      - 'experiment_definition.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt      

    - name: NeuroCI Run
      run: python ./neuroci_code/main.py
